# Generated by Django 5.0.6 on 2024-08-15 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('apk_file', models.FileField(upload_to='apks/')),
                ('first_screen_screenshot', models.FileField(blank=True, null=True, upload_to='screenshots/')),
                ('second_screen_screenshot', models.FileField(blank=True, null=True, upload_to='screenshots/')),
                ('video_recording', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('ui_hierarchy', models.TextField(blank=True, null=True)),
                ('screen_changed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
